#!/bin/bash

set -euo pipefail

SOURCE_DIR=$1
BUILD_DIR=$2

mkdir -p $BUILD_DIR && cd $BUILD_DIR
cmake -S $SOURCE_DIR -B $BUILD_DIR -DCMAKE_CXX_COMPILER=${CXX} -DCONFIG=${BUILD_TYPE} -DFORMAT_FILES_WITH_CLANG_FORMAT_BEFORE_EACH_BUILD=OFF -DCLANG_TIDY_ENABLE=OFF
make -j"$(nproc)"
