cmake_minimum_required(VERSION 3.0.2)

function(flom_add_bin target)
  add_executable(${target}_bin ${target}.cpp)
  set_target_properties(${target}_bin PROPERTIES OUTPUT_NAME ${target})
  flom_set_compile_options(${target}_bin)
  target_link_libraries(${target}_bin PRIVATE flom_lib)
  enable_clang_format(${target}_bin)
  enable_clang_tidy(${target}_bin)
endfunction()
